//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchStockFeedManagerConsole.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BCMYEntities : DbContext
    {
        public BCMYEntities()
            : base("name=BCMYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vProductInfo> vProductInfoes { get; set; }
    
        public virtual ObjectResult<SP_FiterProducts_Result> SP_FiterProducts(string categoryName, string virginOrNot)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            var virginOrNotParameter = virginOrNot != null ?
                new ObjectParameter("virginOrNot", virginOrNot) :
                new ObjectParameter("virginOrNot", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FiterProducts_Result>("SP_FiterProducts", categoryNameParameter, virginOrNotParameter);
        }
    }
}
